---
title: "wasteloadR"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: yeti
    css: styles.css
runtime: shiny
---

```{r, echo=F}
library(shiny)
library(wqTools)
library(leaflet)
library(leaflet.extras)
library(shinybusy)
library(plotly)
library(sortable)
library(shinyWidgets)
#library(waiter)
source('findDataMod.R')
source('permitGaugeMod.R')
source('figuresMod.R')
source('wasteloadR_stats.R')
source('wlStatsMod.R')
permits_coords=read.csv(file="permits_coords.csv")
permits_coords=within(permits_coords, {
	lab=paste0(
		'<p>',
		"Permit ID: ", locationID,
		'<br />', "Name: ", locationName,
		'<br />', "Type: ", locationType)	
})

```

# `r icon("search")` Find data 
```{r, echo=F}
findDataModUI('found_data')
found_data=callModule(module=findDataMod, id='found_data', permits_coords=permits_coords)

## Extract effluent data from findDataMod
effluent_data=reactive({
	req(found_data$ec_data())
	found_data$ec_data()
})

## Extract permit ID from findPermitMod
pid=reactive({gsub(" .*$", "", found_data$pid())})

## Extract wq data
wq_data=reactive({
	req(found_data$wq_data())
	wq_data=found_data$wq_data()
})

```

# `r icon('tachometer-alt')` Effluent charts 
```{r, echo=F}
permitGaugeModUI('permit_gauge1')
permit_gauge1=callModule(module=permitGaugeMod, id='permit_gauge1', effluent_data)
```

# `r icon('chart-line')` Water quality analysis
```{r}
figuresModUI('figures')
figures=callModule(module=figuresMod, id='figures', wq_data)
```

#  `r icon('table')` Wasteload stats

```{r}
wlStatsModUI('wl_stats')
wl_stats=callModule(module=wlStatsMod, id='wl_stats', wq_data)
```















